jenkins:
  systemMessage: "SDLCdemo automatic Jenkins setup\n\n"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
jobs:
  - script: >
      pipelineJob('test') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/uzugic/SDLCdemo' }
                        branch 'master'
                        extensions {}
                    }
                  }
              }
          }
      }
